### PR TITLE
Spelling fixes.

### PR DESCRIPTION
**Pull request by nissa-seru**

### CODE REVIEW

**Comment by nissa-seru** [comment]
Closing stale PR for housekeeping; will make any further changes with a new PR when able.

**Comment by DesperatePeter** [comment]
Something weird seems to have happened here: https://github.com/DesperatePeter/starsector-advanced-weapon-control/pull/26/commits/003144f187f1340d51f63e5cdbcf20c7b718d0a3
Maybe I changed the folder structure without remembering.
Therefore it seems easier for me to simply manually apply the spelling fix. Still, thank you for your contribution!

**Comment by nissa-seru** [comment]
No worries! Ah, sorry, this feels like a lifetime ago - I think that I had something misconfigured with my IDE Github integration at time time. Looking back through, it looks like the only substantive fix was someting->something in the LunaSettings below:

```
agc_enableCustomAI,enableCustomAI,Boolean,true,,"If set to false, weapons will simply not fire if their default AI would target someting forbidden by tags.
```

**Comment by DesperatePeter** [comment]
Yup, I think so!
I simply manually added that fix. Thank you

**Pull request closed without merging**
